if __name__ == '__main__':
    places = ['paris','california','goa','toronto','london']
    print(places)
    print(sorted(places))
    print(places)
    places.sort(reverse=True)
    print(places)
    places.reverse()
    print(places)
    places.reverse()
    print(places)
    places.sort()
    print(places)
    places.sort(reverse=True)
    print(len(places))
